# Demo config
port: 20058
debug: true
receivers:
  - name: without_mention
    targets:
      - url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=d4b9e48f-2f78-49a0-81eb-5414873d24ef

  - name: mention_list
    targets:
      - url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=d4b9e48f-2f78-49a0-81eb-5414873d24ef
        mentioned_list: ["bot", "@all"]  # (text only) userid的列表，提醒群中的指定成员(@某个成员)，@all表示提醒所有人，如果开发者获取不到userid，可以使用mentioned_mobile_list

  - name: mention_mobile
    targets:
      - url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=d4b9e48f-2f78-49a0-81eb-5414873d24ef
        mentioned_mobile_list: ["13800001111", "@all"] # (text only) 手机号列表，提醒手机号对应的群成员(@某个成员)，@all表示提醒所有人
